version: '3.8'
services:
  backend:
    build: ./backend
    expose:
      - "81"
    volumes:
      - ./backend/app:/code/app

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
